services:
  pivio:
    build: .
    ports:
      - "9123:9123"
    links:
      - elasticsearch

  elasticsearch:
    image: opensearchproject/opensearch:2.14.0
    command: ["/bin/sh", "-c", "gosu elasticsearch elasticsearch"]
